#include "Academic_Free_License.h"

//-----------------------------------------------------------------------------

const char * const Academic_Free_License::notice =

"Licensed under the Academic Free License version 2.0"
;

//-----------------------------------------------------------------------------

const char * const Academic_Free_License::full_text =

"The Academic Free License\n"
" v. 2.0\n"
"\n"
"This Academic Free License (the \"License\") applies to any original\n"
"work of authorship (the \"Original Work\") whose owner (the \"Licensor\")\n"
"has placed the following notice immediately following the copyright\n"
"notice for the Original Work:\n"
"\n"
"  Licensed under the Academic Free License version 2.0\n"
"\n"
"1) Grant of Copyright License. Licensor hereby grants You a world-\n"
"   wide, royalty-free, non-exclusive, perpetual, sublicenseable\n"
"   license to do the following:\n"
"\n"
"   a) to reproduce the Original Work in copies;\n"
"\n"
"   b) to prepare derivative works (\"Derivative Works\") based upon the\n"
"      Original Work;\n"
"\n"
"   c) to distribute copies of the Original Work and Derivative Works\n"
"      to the public;\n"
"\n"
"   d) to perform the Original Work publicly; and\n"
"\n"
"   e) to display the Original Work publicly.\n"
"\n"
"2) Grant of Patent License. Licensor hereby grants You a world-wide,\n"
"   royalty-free, non-exclusive, perpetual, sublicenseable license,\n"
"   under patent claims owned or controlled by the Licensor that are\n"
"   embodied in the Original Work as furnished by the Licensor, to\n"
"   make, use, sell and offer for sale the Original Work and\n"
"   Derivative Works.\n"
"\n"
"3) Grant of Source Code License. The term \"Source Code\" means the\n"
"   preferred form of the Original Work for making modifications to it\n"
"   and all available documentation describing how to modify the\n"
"   Original Work.  Licensor hereby agrees to provide a machine-\n"
"   readable copy of the Source Code of the Original Work along with\n"
"   each copy of the Original Work that Licensor distributes.\n"
"   Licensor reserves the right to satisfy this obligation by placing\n"
"   a machine-readable copy of the Source Code in an information\n"
"   repository reasonably calculated to permit inexpensive and\n"
"   convenient access by You for as long as Licensor continues to\n"
"   distribute the Original Work, and by publishing the address of\n"
"   that information repository in a notice immediately following the\n"
"   copyright notice that applies to the Original Work.\n"
"\n"
"4) Exclusions From License Grant. Neither the names of Licensor, nor\n"
"   the names of any contributors to the Original Work, nor any of\n"
"   their trademarks or service marks, may be used to endorse or\n"
"   promote products derived from this Original Work without express\n"
"   prior written permission of the Licensor.  Nothing in this License\n"
"   shall be deemed to grant any rights to trademarks, copyrights,\n"
"   patents, trade secrets or any other intellectual property of\n"
"   Licensor except as expressly stated herein.  No patent license is\n"
"   granted to make, use, sell or offer to sell embodiments of any\n"
"   patent claims other than the licensed claims defined in Section 2.\n"
"   No right is granted to the trademarks of Licensor even if such\n"
"   marks are included in the Original Work.  Nothing in this License\n"
"   shall be interpreted to prohibit Licensor from licensing under\n"
"   different terms from this License any Original Work that Licensor\n"
"   otherwise would have a right to license.\n"
"\n"
"5) This section intentionally omitted.\n"
"\n"
"6) Attribution Rights. You must retain, in the Source Code of any\n"
"   Derivative Works that You create, all copyright, patent or\n"
"   trademark notices from the Source Code of the Original Work, as\n"
"   well as any notices of licensing and any descriptive text\n"
"   identified therein as an \"Attribution Notice.\"  You must cause the\n"
"   Source Code for any Derivative Works that You create to carry a\n"
"   prominent Attribution Notice reasonably calculated to inform\n"
"   recipients that You have modified the Original Work.\n"
"\n"
"7) Warranty of Provenance and Disclaimer of Warranty. Licensor\n"
"   warrants that the copyright in and to the Original Work and the\n"
"   patent rights granted herein by Licensor are owned by the Licensor\n"
"   or are sublicensed to You under the terms of this License with the\n"
"   permission of the contributor(s) of those copyrights and patent\n"
"   rights.  Except as expressly stated in the immediately proceeding\n"
"   sentence, the Original Work is provided under this License on an\n"
"   \"AS IS\" BASIS and WITHOUT WARRANTY, either express or implied,\n"
"   including, without limitation, the warranties of NON-INFRINGEMENT,\n"
"   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  THE ENTIRE\n"
"   RISK AS TO THE QUALITY OF THE ORIGINAL WORK IS WITH YOU.  This\n"
"   DISCLAIMER OF WARRANTY constitutes an essential part of this\n"
"   License.  No license to Original Work is granted hereunder except\n"
"   under this disclaimer.\n"
"\n"
"8) Limitation of Liability. Under no circumstances and under no legal\n"
"   theory, whether in tort (including negligence), contract, or\n"
"   otherwise, shall the Licensor be liable to any person for any\n"
"   direct, indirect, special, incidental, or consequential damages of\n"
"   any character arising as a result of this License or the use of\n"
"   the Original Work including, without limitation, damages for loss\n"
"   of goodwill, work stoppage, computer failure or malfunction, or\n"
"   any and all other commercial damages or losses.  This limitation\n"
"   of liability shall not apply to liability for death or personal\n"
"   injury resulting from Licensor's negligence to the extent\n"
"   applicable law prohibits such limitation.  Some jurisdictions do\n"
"   not allow the exclusion or limitation of incidental or\n"
"   consequential damages, so this exclusion and limitation may not\n"
"   apply to You.\n"
"\n"
"9) Acceptance and Termination. If You distribute copies of the\n"
"   Original Work or a Derivative Work, You must make a reasonable\n"
"   effort under the circumstances to obtain the express assent of\n"
"   recipients to the terms of this License.  Nothing else but this\n"
"   License (or another written agreement between Licensor and You)\n"
"   grants You permission to create Derivative Works based upon the\n"
"   Original Work or to exercise any of the rights granted in Section\n"
"   1 herein, and any attempt to do so except under the terms of this\n"
"   License (or another written agreement between Licensor and You) is\n"
"   expressly prohibited by U.S. copyright law, the equivalent laws of\n"
"   other countries, and by international treaty.  Therefore, by\n"
"   exercising any of the rights granted to You in Section 1 herein,\n"
"   You indicate Your acceptance of this License and all of its terms\n"
"   and conditions.\n"
"\n"
"10) Termination for Patent Action. This License shall terminate\n"
"    automatically and You may no longer exercise any of the rights\n"
"    granted to You by this License as of the date You commence an\n"
"    action, including a cross-claim or counterclaim, for patent\n"
"    infringement (i) against Licensor with respect to a patent\n"
"    applicable to software or (ii) against any entity with respect to\n"
"    a patent applicable to the Original Work (but excluding\n"
"    combinations of the Original Work with other software or\n"
"    hardware).\n"
"\n"
"11) Jurisdiction, Venue and Governing Law. Any action or suit\n"
"    relating to this License may be brought only in the courts of a\n"
"    jurisdiction wherein the Licensor resides or in which Licensor\n"
"    conducts its primary business, and under the laws of that\n"
"    jurisdiction excluding its conflict-of-law provisions.  The\n"
"    application of the United Nations Convention on Contracts for the\n"
"    International Sale of Goods is expressly excluded.  Any use of\n"
"    the Original Work outside the scope of this License or after its\n"
"    termination shall be subject to the requirements and penalties of\n"
"    the U.S. Copyright Act, 17 U.S.C. 101 et seq., the equivalent\n"
"    laws of other countries, and international treaty.  This section\n"
"    shall survive the termination of this License.\n"
"\n"
"12) Attorneys Fees. In any action to enforce the terms of this\n"
"    License or seeking damages relating thereto, the prevailing party\n"
"    shall be entitled to recover its costs and expenses, including,\n"
"    without limitation, reasonable attorneys' fees and costs incurred\n"
"    in connection with such action, including any appeal of such\n"
"    action.  This section shall survive the termination of this\n"
"    License.\n"
"\n"
"13) Miscellaneous. This License represents the complete agreement\n"
"    concerning the subject matter hereof.  If any provision of this\n"
"    License is held to be unenforceable, such provision shall be\n"
"    reformed only to the extent necessary to make it enforceable.\n"
"\n"
"14) Definition of \"You\" in This License. \"You\" throughout this\n"
"    License, whether in upper or lower case, means an individual or a\n"
"    legal entity exercising rights under, and complying with all of\n"
"    the terms of, this License.  For legal entities, \"You\" includes\n"
"    any entity that controls, is controlled by, or is under common\n"
"    control with you.  For purposes of this definition, \"control\"\n"
"    means (i) the power, direct or indirect, to cause the direction\n"
"    or management of such entity, whether by contract or otherwise,\n"
"    or (ii) ownership of fifty percent (50%) or more of the\n"
"    outstanding shares, or (iii) beneficial ownership of such entity.\n"
"\n"
"15) Right to Use. You may use the Original Work in all ways not\n"
"    otherwise restricted or conditioned by this License or by law,\n"
"    and Licensor promises not to interfere with or be responsible for\n"
"    such uses by You.\n"
"\n"
"This license is Copyright (C) 2003 Lawrence E. Rosen.  All rights\n"
"reserved.  Permission is hereby granted to copy and distribute this\n"
"license without modification.  This license may not be modified\n"
"without the express written permission of its copyright owner.\n"
;
