<%@ Page Title="About" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeFile="About.aspx.cs" Inherits="About" %>

<asp:Content ID="BodyContent" ContentPlaceHolderID="MainContent" runat="server">
    <h2><%: Title %></h2>
    <h3>What is the Stochastic Uncertainty Estimator?</h3>
    <p>
	    While SUE can use information generated by statistical analysis (such as the mode, standard deviation, 
        correlation, and regression), it is not designed to do statistical analysis.  Nor is it designed to 
        determine the relationship between variables (i.e., parameters).  Rather SUE provides a method to explore 
        the implications of statistical analyses, particularly regarding prediction uncertainty.  It should be 
        thought of as an exploratory tool that allows one to examine how uncertainty in variables and relationships 
        among variables influences overall uncertainty in a prediction.
    </p>
    <p>
        SUE works by creating a sample space of parameters and conveys requested information about the distribution 
        of those parameters to the user. This might include information about individual parameters (variables) and 
        their relationship in terms of correlation and equations.  The user then can query the sample space about uncertainty. 
    </p>
    <p>
        This is best illustrated by an example. We will use a high-school as our sample space, where each student is a sample. 
        The sample space has parameters: height, age, weight, etc. Some of these parameters can be described by distribution 
        types - for example, we may be able to describe age as uniformly distributed over the interval 14 to 18. We may declare 
        weight to be normally distributed with mean 140 lbs and standard deviation of 20 lbs. We may include a correlation 
        between height and weight.  There may be parameters that can be described as functions of other parameters. For example, 
        perhaps running speed can be described as some function of age, height, and weight. Or perhaps we have a regression that 
        predicts running speed as a function of height and weight. Once these parameters are established we can ask queries.  
        We may wish to know the standard deviation of a certain parameter or perhaps see a histogram of that parameter. We may 
        wish to see the raw sample values of a given parameter for external use or for comparison with real measured numbers to 
        check the accuracy of proposed functions. Or we may want to see how uncertain regression predictions are given 
        uncertainty in the regression parameters.
    </p>
    <p>SUE was developed by Jimm Domingo and Justin Goodman at the Oregon State University <a href="http://www.forestry.oregonstate.edu/">College of Forestry</a> (2002-2004)<br />under the direction of Dr. Mark Harmon</p>
    <p>Source code for SUE can be found on it's <a href="https://github.com/geoSpacer/SUE">gitHub</a> site</p>

</asp:Content>
